/**
 * Expression API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Expression from './Expression';

/**
 * The FilterForecast model module.
 * @module model/FilterForecast
 * @version 1.0.0
 */
class FilterForecast {
    /**
     * Constructs a new <code>FilterForecast</code>.
     * @alias module:model/FilterForecast
     * @extends module:model/Expression
     * @implements module:model/Expression
     */
    constructor() { 
        Expression.initialize(this);
        FilterForecast.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilterForecast</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FilterForecast} obj Optional instance to populate.
     * @return {module:model/FilterForecast} The populated <code>FilterForecast</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilterForecast();
            Expression.constructFromObject(data, obj);
            Expression.constructFromObject(data, obj);

            if (data.hasOwnProperty('externalIds')) {
                obj['externalIds'] = ApiClient.convertToType(data['externalIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FilterForecast</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FilterForecast</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['externalIds'])) {
            throw new Error("Expected the field `externalIds` to be an array in the JSON data but got " + data['externalIds']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} externalIds
 */
FilterForecast.prototype['externalIds'] = undefined;


// Implement Expression interface:
/**
 * @member {String} @type
 */
Expression.prototype['@type'] = undefined;




export default FilterForecast;

