/**
 * Expression API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Attributes from './Attributes';
import Expression from './Expression';

/**
 * The PositionNode model module.
 * @module model/PositionNode
 * @version 1.0.0
 */
class PositionNode {
    /**
     * Constructs a new <code>PositionNode</code>.
     * @alias module:model/PositionNode
     * @extends module:model/Expression
     * @implements module:model/Expression
     */
    constructor() { 
        Expression.initialize(this);
        PositionNode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PositionNode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PositionNode} obj Optional instance to populate.
     * @return {module:model/PositionNode} The populated <code>PositionNode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PositionNode();
            Expression.constructFromObject(data, obj);
            Expression.constructFromObject(data, obj);

            if (data.hasOwnProperty('ref')) {
                obj['ref'] = ApiClient.convertToType(data['ref'], 'String');
            }
            if (data.hasOwnProperty('brief')) {
                obj['brief'] = ApiClient.convertToType(data['brief'], 'String');
            }
            if (data.hasOwnProperty('scheduled')) {
                obj['scheduled'] = ApiClient.convertToType(data['scheduled'], 'Boolean');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = Attributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('expression')) {
                obj['expression'] = Expression.constructFromObject(data['expression']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PositionNode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PositionNode</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ref'] && !(typeof data['ref'] === 'string' || data['ref'] instanceof String)) {
            throw new Error("Expected the field `ref` to be a primitive type in the JSON string but got " + data['ref']);
        }
        // ensure the json data is a string
        if (data['brief'] && !(typeof data['brief'] === 'string' || data['brief'] instanceof String)) {
            throw new Error("Expected the field `brief` to be a primitive type in the JSON string but got " + data['brief']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          Attributes.validateJSON(data['attributes']);
        }
        // validate the optional field `expression`
        if (data['expression']) { // data not null
          Expression.validateJSON(data['expression']);
        }

        return true;
    }


}



/**
 * @member {String} ref
 */
PositionNode.prototype['ref'] = undefined;

/**
 * @member {String} brief
 */
PositionNode.prototype['brief'] = undefined;

/**
 * @member {Boolean} scheduled
 */
PositionNode.prototype['scheduled'] = undefined;

/**
 * @member {module:model/Attributes} attributes
 */
PositionNode.prototype['attributes'] = undefined;

/**
 * @member {module:model/Expression} expression
 */
PositionNode.prototype['expression'] = undefined;


// Implement Expression interface:
/**
 * @member {String} @type
 */
Expression.prototype['@type'] = undefined;




export default PositionNode;

