openapi: 3.0.1
info:
  title: Expression API
  version: 1.0.0
paths:
  /expressions:
    get:
      summary: "Get a list of expressions"
      responses:
        '200':
          description: A list of expressions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expression'
components:
  schemas:
    Expression:
      type: object
      discriminator:
        propertyName: '@type'
        mapping:
          FilterForecast: '#/components/schemas/FilterForecast'
          FilterSophon: '#/components/schemas/FilterSophon'
          Function: '#/components/schemas/Function'
          Operation: '#/components/schemas/Operation'
          PositionNode: '#/components/schemas/PositionNode'
          PositionReference: '#/components/schemas/PositionReference'
      properties:
        '@type':
          type: string

    FilterForecast:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            externalIds:
              type: array
              items:
                type: string

    FilterSophon:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            side:
              $ref: '#/components/schemas/SophonSide'
            flags:
              type: array
              items:
                type: string
            venues:
              type: array
              items:
                type: string
            entities:
              type: array
              items:
                type: string
            platforms:
              type: array
              items:
                type: string

    Function:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            expressions:
              type: array
              items:
                $ref: '#/components/schemas/Expression'
            functionType:
              $ref: '#/components/schemas/FunctionType'

    Operation:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            left:
              $ref: '#/components/schemas/Expression'
            right:
              $ref: '#/components/schemas/Expression'
            operatorType:
              $ref: '#/components/schemas/OperatorType'

    PositionNode:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            ref:
              type: string
            brief:
              type: string
            scheduled:
              type: boolean
            attributes:
              $ref: '#/components/schemas/Attributes'
            expression:
              $ref: '#/components/schemas/Expression'

    PositionReference:
      allOf:
        - $ref: '#/components/schemas/Expression'
        - type: object
          properties:
            ref:
              type: string

    Attributes:
      type: object
      properties:
        validSince:
          type: string
          format: date
        validUntil:
          type: string
          format: date
        validReports:
          type: array
          items:
            type: string

    SophonSide:
      type: string
      enum:
        - BUY
        - SELL
        - BOTH

    FunctionType:
      type: string
      enum:
        - SUM
        - NEGATE

    OperatorType:
      type: string
      enum:
        - ADD
        - SUBTRACT
        - TIMES
        - DIVIDE
